[WIP] Add camera preview and checks before joining event
veertly/app pull request #101
Opened 2020-06-01 10:49 UTC by harish-aka-shivi

Add the preview and checks
- [x] Ask permission
- [x] Add modal with camera stream
- [ ] Add video and audio devices options
- [ ] Improve UI
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-06-24 07:48 UTC, joaoaguiam requested changes
@harish-aka-shivi Can you please merge this branch with the stage code? I feel there will be some conflicts. Please check the conference room container as I have changed some logic there.

2020-06-24 07:48 UTC, joaoaguiam commented on src/Hooks/useJitsi.js
> +  domain="meet.jit.si",
This should not be hardcoded here, but instead, use a constant like the one we have on Modules/jitsi.js: DEFAULT_JITSI_SERVER

2020-06-24 07:48 UTC, joaoaguiam commented on src/Hooks/useJitsi.js
> +  conferenceVideoType="JITSI",
I am not sure that we should have the conferenceVideoType on this hook. 
We have two options:
- Remove the jitsi part from the conference container and create a new component just for the jitsi main stage that will call use jitsi
- Have a "enabled" variable on the useJitsi hook instead of this one

I would prefer the first option, it's cleaner. What do you think?

2020-06-24 07:48 UTC, joaoaguiam commented on src/Hooks/useJitsi.js
>      if (conferenceVideoType === "JITSI" && loaded && lastRoomLoaded !== roomName) {
I have changed this condition on the conference container because of the backstage feature. Can you please check the differences here: https://github.com/veertly/app/commit/42e1a09f9823c701aec6b79df1da6b613f1d15d3#diff-46c206b34a00a81456a8dc5c2612989d

2020-06-24 07:48 UTC, joaoaguiam commented on src/Containers/EventSession/ConferenceRoomContainer.js
> +  // useEffect(() => {
Let's not keep this code commented out :P

2020-06-24 11:52 UTC, harish-aka-shivi commented on src/Hooks/useMuteAudioVideo.js
> +  const [muteAudioVideoState, setMuteAudioVideoState] = useLocalStorage("vrtly_mute_audio_video_state", {});
Yes, just tried keeping it short, Anyways need the key to be in the same format as others

2020-06-24 12:00 UTC, harish-aka-shivi commented on src/Hooks/useShowTechCheck.js
> +  const [techCheckState, setTechCheckState] = useLocalStorage("vrtly_show_tech_check", {});
Will fix it.

2020-06-24 12:02 UTC, harish-aka-shivi commented on src/Hooks/useJitsi.js
> +  domain="meet.jit.si",
Right. will do that

2020-06-24 13:18 UTC, harish-aka-shivi commented on src/Hooks/useJitsi.js
> +  conferenceVideoType="JITSI",
Yes, I added a separate component for the main stage. I was trying it with networking area also but It was leading to reinitializing the component, so sticking with calling hooks in networking containers.

2020-06-24 13:28 UTC, harish-aka-shivi commented on src/Hooks/useJitsi.js
>      if (conferenceVideoType === "JITSI" && loaded && lastRoomLoaded !== roomName) {
I don't understand this code
```
 if (eventSessionDetails.conferenceVideoType !== "JITSI" && loaded) {
      // dispose existing jitsi
      if (jitsiApi) {
        jitsiApi.executeCommand("hangup");
        jitsiApi.dispose();
        setLastRoomLoaded(null);
      }
    }
```

If we are not initializing jitsi when it is not of type Jitsi, how will it be true any time?

2020-06-24 13:36 UTC, joaoaguiam commented on src/Hooks/useJitsi.js
>      if (conferenceVideoType === "JITSI" && loaded && lastRoomLoaded !== roomName) {
This happened when one changes the type of event from jitsi to livestream on the cockpit, if the page is loaded, it then still keeps the jitsi component in the screen. You can try by running the cockpit and change back and forth the type of event.

2020-06-25 05:52 UTC, harish-aka-shivi commented on src/Containers/EventSession/ConferenceRoomContainer.js
> +  const subject = "Main Stage";
Done, 👍

2020-06-25 12:56 UTC, harish-aka-shivi commented on src/Hooks/useJitsi.js
>      if (conferenceVideoType === "JITSI" && loaded && lastRoomLoaded !== roomName) {
So, I handled differently. so when event type changes, I am disposing of the jitsiAPI instance. I tried setting values In the Cockpit and couldn't  reproduce it

2020-06-25 13:26 UTC, merged

2020-10-06 18:37 UTC, hightechgrace commented on src/Containers/EventSession/ConferenceRoomContainer.js
> +  const subject = "Main Stage";
Awesome